const LESSONS = {
  family: {
    name: 'Семья 👩🏼‍❤️‍👨🏻',
    description: 'Elders, Dull moment, Niece etc.',
    items: [
      { ru: "Культурные Традиции", en: "Cultural traditions" },
      { ru: "Единственный ребенок", en: "An only child" },
      { ru: "Семейная честь", en: "Family honour" },
      { ru: "Пожилые люди", en: "Elders" },
      { ru: "Скучный момент", en: "Dull moment" },
      { ru: "Уровень рождаемости снизился", en: "The birth rate has dropped" },
      { ru: "Имеет приоритет", en: "Take priority" },
      { ru: "Вечерняя прогулка", en: "Evening stroll" },
      { ru: "Оставаться большой частью жизни", en: "Remain a big part of our life" },
      { ru: "По маминой линии", en: "Maternal" },
      { ru: "Идея чистого пространства", en: "Concept of privacy" },
      { ru: "Поддержка", en: "Support" },
      { ru: "Подчиняться авторитетам (Послушный, послушание)", en: "Obey (Obedient, obedience) authority" },
      { ru: "Племянник", en: "Nephew" },
      { ru: "Племянница", en: "Niece" },
      { ru: "Вдова/Вдовец", en: "Widow/Widower" },
      { ru: "Свадьба", en: "Wedding" },
      { ru: "Женитьба", en: "Marriage" },
      { ru: "Расширенная/ Ближайшие/ Нуклеарная семья", en: "Extended / Immediate / Nuclear family" },
      { ru: "Родственники", en: "Relations" },
      { ru: "Поколение", en: "Generation" },
      { ru: "Предок", en: "Ancestor" },
      { ru: "Быть помолвленным", en: "Be engaged" },
      { ru: "Быть разведённым", en: "Be divorced" },
      { ru: "Быть женатым / замужем", en: "Be married" },
      { ru: "Приёмная семья", en: "Foster family" },
      { ru: "Источник любви и жизни", en: "Cradle of love and life" },
      { ru: "Быть разлучённы", en: "Be separated" },
      { ru: "Семейные узы", en: "Family bonds" },
      { ru: "Плохо отражаться", en: "Reflect badly on" },
      { ru: "Родные братья и сестры", en: "Siblings" }
    ]
  },
  family2: {
    name: 'Семья 2 👩🏼‍❤️‍👨🏻',
    description: 'Family idioms and expressions',
    items: [
      { ru: "Быть главой семьи", en: "Wear trousers in the family"},
      { ru: "Наткнуться", en: "Come across"},
      { ru: "Почувствовать близость к", en: "Feel close to"},
      { ru: "Быть чьей-то плотью и кровью", en: "Be one’s flesh and blood"},
      { ru: "Иметь уважение к", en: "Have respect for"},
      { ru: "Зайти к", en: "Come over"},
      { ru: "Быть белой вороной", en: "Be the black sheep in the family"},
      { ru: "Заболеть", en: "Come down with"},
      { ru: "Быть привязанным к", en: "Be attached to"},
      { ru: "Быть светом очей", en: "Be the apple of the eyes"},
      { ru: "Унаследовать", en: "Come into"},
      { ru: "Стыдиться", en: "Be ashamed of"},
      { ru: "Придумать", en: "Come up with"},
      { ru: "Спорить о", en: "Argue about"},
      { ru: "Держаться самому по себе", en: "Keep to oneself"},
      { ru: "Вмешиваться в", en: "Interfere in"},
      { ru: "Это тебя не касается", en: "It doesn’t concern you"},
      { ru: "Давать / нарушать обещание", en: "Make / break a promise"},
      { ru: "Задира́ться, нарываться на ссоры", en: "Pick fights"},
      { ru: "Выпендриваться", en: "Show off"},
      { ru: "Переваливать вину на", en: "Put the blame on"},
      { ru: "Быть довольным чем-либо / кем-либо", en: "Be pleased with"},
      { ru: "Одобрять", en: "Approve of"},
      { ru: "Возражать против", en: "Object to doing"},
      { ru: "Быть популярным среди", en: "Be popular with"}
    ]
  },
    stress1: {
      name: 'Стресс 😬',
      description: 'Stress, emotions and behaviour',
      items: [
        { ru: "Возрастать", en: "Mount" },
        { ru: "На кануне экзаменов", en: "Run up to exams" },
        { ru: "В кратце", en: "In a nutshell" },
        { ru: "Напряжённый", en: "Tense" },
        { ru: "Мелкий", en: "Shallow" },
        { ru: "Держать в тонусе", en: "Keep you on your toes" },
        { ru: "На долгий период", en: "In the long term" },
        { ru: "Облегчить ношу", en: "Lighten the load" },
        { ru: "Анализировать рационально", en: "Analyse rationally" },
        { ru: "Справляться со стрессом", en: "Handle / cope stress" },
        { ru: "Питательная еда", en: "Nutritious meal" },
        { ru: "Важный", en: "Essential" },
        { ru: "Позитивный настрой", en: "Positive attitude" },
        { ru: "Излить душу", en: "Get off the chest" },
        { ru: "Очень надоесть", en: "Be sick and tired of" },
        { ru: "Расстраиваться", en: "Get down" },
        { ru: "Больше не могу выдержать", en: "I can’t take it any more" },
        { ru: "Не преувеличивать", en: "Don’t get things out of proportion" },
        { ru: "Потерять контроль", en: "Lose temper" },
        { ru: "Чувствовать напряжение", en: "Feel the strain" },
        { ru: "Доставлять проблемы", en: "Give a hard time" },
        { ru: "Быть на высоте в чьих-то глазах", en: "Be up to one’s eyes" },
        { ru: "Не принимать близко к сердцу", en: "Take it easy" },
        { ru: "Чувствовать подавленным", en: "Feel overwhelmed" },
        { ru: "Огрызаться", en: "Snarl" },
        { ru: "Заикаться", en: "Stammer" },
        { ru: "Шептать", en: "Whisper" },
        { ru: "Вздохнуть", en: "Sigh" },
        { ru: "Стонать", en: "Groan" }
      ]
    },
      bodyLanguageAndBehaviour: {
      name: 'Жесты и Поведение 🤌🏻',
      description: 'Physical reactions, gestures, emotions and social behaviour.',
      items: [
        { ru: "Покачать головой", en: "Shake the head" },
        { ru: "Сжать кулаки", en: "Clench the fists" },
        { ru: "Пожать плечами", en: "Shrug the shoulders" },
        { ru: "Сложить руки", en: "Fold the arms" },
        { ru: "Покраснеть от смущения", en: "Blush with embarrassment" },
        { ru: "Топнуть ногой", en: "Stamp the feet" },
        { ru: "Дрожать в страхе", en: "Tremble in fear" },
        { ru: "Стучать пальцами", en: "Tap the finger" },
        { ru: "Совершить преступление", en: "Commit a crime" },
        { ru: "Агрессивная толпа", en: "Rough crowd" },
        { ru: "Задираться, придираться", en: "Pick on" },
        { ru: "Соответствовать", en: "Fit in with" },
        { ru: "Убеждать", en: "Persuade" },
        { ru: "Разубеждать", en: "Dissuade" },
        { ru: "Сдаться", en: "Give in" },
        { ru: "Сопротивляться", en: "Resist" },
        { ru: "Придумать 101 причину", en: "Think of a hundred and one reasons" },
    
        { ru: "Быть неуверенным", en: "Be in two minds" },
        { ru: "Быть в растерянности", en: "Be at sixes and sevens" },
        { ru: "Приютить (в гости)", en: "Put up" },
        { ru: "Унижать, обзывать", en: "Put down" },
        { ru: "Надевать", en: "Put on" },
        { ru: "Откладывать", en: "Put off" },
        { ru: "Мириться с", en: "Put up with" },
        { ru: "Влияние на", en: "Influence on" },
        { ru: "Обращать внимание на", en: "Pay attention to" },
        { ru: "Производить впечатление на", en: "Make an impression on" },
        { ru: "Настаивать на", en: "Insist on" },
        { ru: "Хвастаться о", en: "Boast about" }
      ]
    }
};
